# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Nogfx < Formula
  desc ""
  homepage ""
  version "0.0.13"
  license "MIT"

  on_macos do
    if Hardware::CPU.intel?
      url "https://github.com/tobiassjosten/nogfx/releases/download/0.0.13/nogfx_0.0.13_darwin_amd64.tar.gz"
      sha256 "e6588085b938c1a09541404ba07ff14f0fa6e8d238079474ea271b31f00adff4"

      def install
        bin.install "nogfx"
      end
    end
    if Hardware::CPU.arm?
      url "https://github.com/tobiassjosten/nogfx/releases/download/0.0.13/nogfx_0.0.13_darwin_arm64.tar.gz"
      sha256 "c86a263ecdf9d9c92468788f4b82b4364924b02a668564ebfe01ed7d5fc1672e"

      def install
        bin.install "nogfx"
      end
    end
  end

  on_linux do
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/tobiassjosten/nogfx/releases/download/0.0.13/nogfx_0.0.13_linux_arm64.tar.gz"
      sha256 "d85d43bad8159a2205aa902d36fd2831c19dee555bc5c4e9495545685eb9930f"

      def install
        bin.install "nogfx"
      end
    end
    if Hardware::CPU.intel?
      url "https://github.com/tobiassjosten/nogfx/releases/download/0.0.13/nogfx_0.0.13_linux_amd64.tar.gz"
      sha256 "37df3f4353110e21635e87e4f626347a88016cb7310795e5d6468d3646b24edb"

      def install
        bin.install "nogfx"
      end
    end
  end
end
