# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Nogfx < Formula
  desc ""
  homepage ""
  version "0.0.9"
  license "MIT"

  on_macos do
    if Hardware::CPU.arm?
      url "https://github.com/tobiassjosten/nogfx/releases/v0.0.9/nogfx_0.0.9_darwin_arm64.tar.gz"
      sha256 "c756631f88c540bfaf3f971594a258a8e86777e8863f9d55177cd39bf6358f66"

      def install
        bin.install "nogfx"
      end
    end
    if Hardware::CPU.intel?
      url "https://github.com/tobiassjosten/nogfx/releases/v0.0.9/nogfx_0.0.9_darwin_amd64.tar.gz"
      sha256 "34f70cb19163354c98dd98126758570013f37ad93c5f90d4818a20691ca389cc"

      def install
        bin.install "nogfx"
      end
    end
  end

  on_linux do
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/tobiassjosten/nogfx/releases/v0.0.9/nogfx_0.0.9_linux_arm64.tar.gz"
      sha256 "5400ae4ff92ab377400b37b7b6783d03684043245523eb881633fc6d24a8a525"

      def install
        bin.install "nogfx"
      end
    end
    if Hardware::CPU.intel?
      url "https://github.com/tobiassjosten/nogfx/releases/v0.0.9/nogfx_0.0.9_linux_amd64.tar.gz"
      sha256 "24392fd3f634160965b6a5b4581b0c0ba1ce2cc2b2647d35d0caf380543aa3ca"

      def install
        bin.install "nogfx"
      end
    end
  end
end
