# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Nogfx < Formula
  desc ""
  homepage ""
  version "0.0.11"
  license "MIT"

  on_macos do
    if Hardware::CPU.arm?
      url "https://github.com/tobiassjosten/nogfx/releases/download/v0.0.11/nogfx_0.0.11_darwin_arm64.tar.gz"
      sha256 "3b6a93dcb072e7fba9a30a8be4bdffadca098d0deae88a462c362e71ae1a2e1a"

      def install
        bin.install "nogfx"
      end
    end
    if Hardware::CPU.intel?
      url "https://github.com/tobiassjosten/nogfx/releases/download/v0.0.11/nogfx_0.0.11_darwin_amd64.tar.gz"
      sha256 "0878aa043628b3d22f0e52ac0035809caa2be5984a7030e1549be0a55af3e4a1"

      def install
        bin.install "nogfx"
      end
    end
  end

  on_linux do
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/tobiassjosten/nogfx/releases/download/v0.0.11/nogfx_0.0.11_linux_arm64.tar.gz"
      sha256 "2eb9f5c51919230c679797a5ca33d3f99732ce610d3e0e82698bb510f6ff2f4f"

      def install
        bin.install "nogfx"
      end
    end
    if Hardware::CPU.intel?
      url "https://github.com/tobiassjosten/nogfx/releases/download/v0.0.11/nogfx_0.0.11_linux_amd64.tar.gz"
      sha256 "e389248e7dfddc02e1fff508512b3a8e54c2d7e41c49c5ab7ba0ba8e0d4f2951"

      def install
        bin.install "nogfx"
      end
    end
  end
end
